fix: 修復 github actions 觸發的問題
報錯訊息：
error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

解決方法：
`npm i --save-dev @types/node`